### ISSUE TITLE
Issue when hovering mouse in M+ Dungeons list

### ISSUE THREAD

**Issue by MuTLY** [NumyAddon/MythicPlusTweaks#4] opened 2024-04-02 23:48 UTC
Getting errors when hovering mouse over the dungeon list (boxes on the bottom part of the Blizzard's UI).

```
17x ...dOns/MythicPlusTweaks/modules/dungeonIconTooltip.lua:81: attempt to index local 'color' (a nil value)
[string "@MythicPlusTweaks/modules/dungeonIconTooltip.lua"]:81: in function `ProcessAffixScores'
[string "@MythicPlusTweaks/modules/dungeonIconTooltip.lua"]:56: in function `OnTooltipShow'
[string "@MythicPlusTweaks/modules/dungeonIconTooltip.lua"]:15: in function <...dOns/MythicPlusTweaks/modules/dungeonIconTooltip.lua:14>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@MythicPlusTweaks/modules/dungeonTeleports.lua"]:196: in function <MythicPlusTweaks/modules/dungeonTeleports.lua:195>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 SecureHookScript = <function> defined @ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:409
 defaultModuleLibraries = <table> {
 }
 RawHookScript = <function> defined @ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:394
 GetName = <function> defined @MythicPlusTweaks/modules/dungeonIconTooltip.lua:27
 GetOptions = <function> defined @MythicPlusTweaks/modules/dungeonIconTooltip.lua:35
 OnTooltipShow = <function> defined @MythicPlusTweaks/modules/dungeonIconTooltip.lua:48
 name = "MythicPlusTweaks_DungeonIconTooltip"
 IsEnabled = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 ProcessAffixScores = <function> defined @MythicPlusTweaks/modules/dungeonIconTooltip.lua:67
 HookScript = <function> defined @ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:365
 IsHooked = <function> defined @ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:492
 IsModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:213
 SetDefaultModuleState = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 baseName = "MythicPlusTweaks"
 MapIdIsAddedToTooltip = <function> defined @MythicPlusTweaks/modules/dungeonIconTooltip.lua:89
 SetEnabledState = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:273
 enabledState = true
 GetDescription = <function> defined @MythicPlusTweaks/modules/dungeonIconTooltip.lua:31
 OnDisable = <function> defined @MythicPlusTweaks/modules/dungeonIconTooltip.lua:23
 OnEnable = <function> defined @MythicPlusTweaks/modules/dungeonIconTooltip.lua:9
 hooks = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 SecureHook = <function> defined @ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:335
 IterateModules = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 UnhookAll = <function> defined @ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:476
 RawHook = <function> defined @ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:312
 Unhook = <function> defined @ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:417
 moduleName = "DungeonIconTooltip"
 defaultModuleState = true
 Disable = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
}
linesLeft = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
}
linesRight = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
}
affixScores = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
higherScore = 172
higherAffix = "Fortified"
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 ```

**Comment by Numynum** [comment] 2024-04-03 07:01
Caused by https://github.com/Stanzilla/WoWUIBugs/issues/544, will look into a workaround for now

**Comment by Numynum** [comment] 2024-04-03 08:49
seems to already have been fixed by blizzard 🙂

**Comment by Numynum** [comment] 2024-04-03 08:52
folks from US realms are saying it's still broken there, might still look into a workaround for now 🤔

**Comment by Numynum** [comment] 2024-04-03 09:54
should be fixed with next update 👌

**Closed as completed by Numynum** 2024-04-03 09:54 UTC
Labels: bug, blame blizzard
